### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Madokadaisuki** [lovezzzxxx/livemonitor#1]
![image](https://user-images.githubusercontent.com/61020199/75810222-889eaa80-5dcd-11ea-9fb1-1e6503df855f.png)
对酸酸乳代理进行设置以后一直循环这样的error报告，哪怕是换了其他端口代理或是直接不使用代理仍旧如此，nonebot运行正常指令也都有回应，无法排查到原因所以特此请教

**Comment by lovezzzxxx** [comment]
如果所有的监视器都返回error的话应该是梯子的问题，可以检查一下ssr设置里允许来自局域网的链接是否打开，或者换用v2ray代理工具（理论上这两种工具开启全局代理后即使指定proxy参数也会通过代理访问）
如果只是twitter出错那么可能是推特cookies设置不正确，请确保在网页登陆后再获取cookies，并且按照json格式写入设置文件中（形如"abc": "123"，以逗号,分隔）

**Comment by Madokadaisuki** [comment]
实在是抱歉没用过python，我进行登陆后尝试获取了twitter的cookies并将它填入cookies设置这一栏中，但是仍旧反复出现推特出错的问题，想请问怎么样才能获取到正确的cookies？cookies填写的范例是什么？

**Comment by lovezzzxxx** [comment]
`"cookies": {"_ga":"12345678","_gid":"12345678","_twitter_sess":"12345678","ads_prefs":"\"12345678\"","auth_token":"12345678","csrf_same_site":"12345678","csrf_same_site_set":"12345678","ct0":"12345678","dnt":"12345678","gt":"12345678","guest_id":"12345678","kdt":"12345678","lang":"12345678","personalization_id":"\"12345678\"","remember_checked_on":"12345678","rweb_optin":"12345678","twid":"u=12345678"},`

呃 差不多是这样的感觉？
