### ISSUE TITLE
"word_dic"可否加入正则表达式匹配的功能？

### ISSUE THREAD

**Issue by wjz2001** [lovezzzxxx/livemonitor#15]
这样的话也可以匹配任意直播标题了，毕竟无法推测下一次的直播标题

**Comment by chelomei** [comment]
一般只需要匹配频道号/直播间号就可以了，除非需要过滤出“Β限”一类的时候，才需要利用到关键字词。

**Comment by wjz2001** [comment]
> 一般只需要匹配频道号/直播间号就可以了，除非需要过滤出“Β限”一类的时候，才需要利用到关键字词。

也就是只要空着"word_dic"不填只填vip_dic就可以匹配所有标题？

**Comment by chelomei** [comment]
，

> > 一般只需要匹配频道号/直播间号就可以了，除非需要过滤出“Β限”一类的时候，才需要利用到关键字词。
> 
> 也就是只要空着"word_dic"不填只填vip_dic就可以匹配所有标题？

是的，可以这样使用的。
