### ISSUE TITLE
getyoutubevideodic error

### ISSUE THREAD

**Issue by Akegarasu** [lovezzzxxx/livemonitor#3]
getyoutubevideodic error
确认频道号没错了 测试spider.json也是会有这个毛病
服务器是vultr的
python3.5

**Comment by lovezzzxxx** [comment]
脚本是在python3.8写的，在python3.6简单的运行过似乎也没有问题
如果只是偶尔出现的话应该问题不大，如果所有的监视器都出现这个问题的话可能时ip被youtube封了？可以试试能否正常获取youtube频道或视频页面

**Comment by Akegarasu** [comment]
youtube的监视器都用不了 其他的都是正常的
使用最新release的exe win7系统测试正常了
更换多个各个地区的服务器测试了
使用ubuntu、windows的python3.5、3.6都不行，只有release的exe可以用
是不是release的代码和新的comment不一样了导致的呢
反编译出来看不出来到底哪里不一样

**Comment by Akegarasu** [comment]
![C`S{~0 H%@NRBJRXSFZ04LS](https://user-images.githubusercontent.com/36563862/77490872-2b02f880-6e77-11ea-8fc2-be542c543168.png)
找到原因了：没安装lxml
