### ISSUE TITLE
是否可以加入直播推送色彩惩罚机制的定时恢复机制？

### ISSUE THREAD

**Issue by chelomei** [lovezzzxxx/livemonitor#4]
相对比较长的直播可能会多次提到，并且可能有高密度的提及关键词的评论，可能会直接消耗完推送次数。
如果可以添加一个可设定时间的恢复机制也许可以解决这个问题？

**Comment by lovezzzxxx** [comment]
嗯 这个应该可以有，看看下个版本能不能加入吧（躺

**Comment by lovezzzxxx** [comment]
加上了，不过测试得还不多😂
设置regen参数应该就可以了，还可以设置regen_amount来设置每次恢复的量
