### ISSUE TITLE
如果加入被删除的推文内容显示的功能，应该可以更好地判断活动情况。

### ISSUE THREAD

**Issue by chelomei** [lovezzzxxx/livemonitor#5]
A转推B的推文，B自己删除推文的话似乎也会被推特算作A推文数量-1，（例如今天如月早上删除开播推会被误以为mea在删推）。
如果能加入被删除的推文显示的功能，也许能够更好的判断是否是本人在活动？

**Comment by lovezzzxxx** [comment]
因为获取推文列表只会返回前面十几条推文 为了避免遍历导致过于频繁的请求 只能在这个范围里进行删推的判断，这样的话这个功能做出来会不会有点鸡肋😂

**Comment by chelomei** [comment]
有解决办法了，同时给我推送一下如月noe的推文变化对比一下就可以了
