### ISSUE TITLE
gettwitteruser : 'ct0'

### ISSUE THREAD

**Issue by lemonno2333** [lovezzzxxx/livemonitor#8]
这个是截图
![屏幕截图 2021-02-03 095404](https://user-images.githubusercontent.com/49359040/106686754-ddfac180-6605-11eb-9ad4-10ed943bb9bc.jpg)

**Comment by lovezzzxxx** [comment]
看上去是提供的cookies里没有ct0这一项，twitter的cookies应该是[这样](https://github.com/lovezzzxxx/livemonitor#%E8%BF%90%E8%A1%8C%E5%90%8E%E5%87%BA%E7%8E%B0%E5%BE%88%E5%A4%9Aerror%E4%BF%A1%E6%81%AF)，再检查一下配置文件看看？

**Comment by lemonno2333** [comment]
如果要指定ip的话是怎么加呢

**Comment by lemonno2333** [comment]
![屏幕截图 2021-02-03 225455](https://user-images.githubusercontent.com/49359040/106764569-dd4c4480-6672-11eb-8c88-f0b64c89c900.jpg)
还有这样的

**Comment by chelomei** [comment]
> 如果要指定ip的话是怎么加呢
"type": "qq_user"
"id": 123456
**"ip": "xx.xx.xx.xx"**
"port": 5700

**Comment by chelomei** [comment]
> ![屏幕截图 2021-02-03 225455](https://user-images.githubusercontent.com/49359040/106764569-dd4c4480-6672-11eb-8c88-f0b64c89c900.jpg)
> 还有这样的

这类错误多半是配置文件的问题
可以尝试使用https://jsoneditoronline.org 或者notepad++查看

**Comment by lemonno2333** [comment]
![屏幕截图 2021-02-04 092617](https://user-images.githubusercontent.com/49359040/106831601-262fe780-66cb-11eb-8d30-87665f1b7b82.jpg)
我在go-cqhttp里面的http是0.0.0.0:5700但是并不能推送消息

**Comment by chelomei** [comment]
> ![屏幕截图 2021-02-04 092617](https://user-images.githubusercontent.com/49359040/106831601-262fe780-66cb-11eb-8d30-87665f1b7b82.jpg)
> 我在go-cqhttp里面的http是0.0.0.0:5700但是并不能推送消息

发送消息段需要指定IP（不选择为默认为本地127.0.0.1）。0.0.0.0意为ipv4端任意IP地址或未获取IP地址时的本机，只能作为接收端表示监听任意地址，不可作为发送端IP目标。

**Comment by lemonno2333** [comment]
成了，谢谢dalao，麻烦你了

**Comment by wjz2001** [comment]
> 成了，谢谢dalao，麻烦你了

可以借用一下你的spider.json和go-cqhttp的配置文件吗？我出现了和你类似的问题（不过是127.0.0.1:5700拒绝通信）
